version: '3'

services:
  api-rust:
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: ${DATABASE_CONTAINER_URL}
  postgres:
    ports:
    - 6500:5432

  pgadmin:
    ports:
      - 5050:80